In [ ]:
import pandas as pd

exam_data = {'Physics':[43,68,25,89], 'Chemistry' : [43,68,25,89],'Maths': [43,68,25,89], 'Biology' : [43,68,25,89]}
print(exam_data)

df = pd.DataFrame(exam_data, index = ['S1','S2','S3','S4'])
print(df)

df2 = df.copy()
print(df2.drop('Physics', axis = 1))

{'Physics': [43, 68, 25, 89], 'Chemistry': [43, 68, 25, 89], 'Maths': [43, 68, 25, 89], 'Biology': [43, 68, 25, 89]}
    Physics  Chemistry  Maths  Biology
S1       43         43     43       43
S2       68         68     68       68
S3       25         25     25       25
S4       89         89     89       89
    Chemistry  Maths  Biology
S1         43     43       43
S2         68     68       68
S3         25     25       25
S4         89     89       89

In [ ]:
df2.drop(['S1','S3'])
df2

    Physics  Chemistry  Maths  Biology
S1       43         43     43       43
S2       68         68     68       68
S3       25         25     25       25
S4       89         89     89       89

In [ ]:
df2.drop(['Physics', 'Chemistry'], axis = 1)

    Maths  Biology
S1     43       43
S2     68       68
S3     25       25
S4     89       89

In [ ]:
s1_data = df2.iloc[0,:]
print(s1_data)
s1_data = df2.loc['S1']
print(s1_data)

Physics      43
Chemistry    43
Maths        43
Biology      43
Name: S1, dtype: int64


Physics      43
Chemistry    43
Maths        43
Biology      43
Name: S1, dtype: int64

In [ ]:
s1_s3_data = df2.iloc[[0,2],:]
print(s1_s3_data,'\n\n')
s1_s3_data = df2.loc[['S1','S3']]
print(s1_s3_data)

    Physics  Chemistry  Maths  Biology
S1       43         43     43       43
S3       25         25     25       25


    Physics  Chemistry  Maths  Biology
S1       43         43     43       43
S3       25         25     25       25

In [ ]:
math_marks = df2.iloc[:,2]
print(math_marks,'\n\n')
math_marks = df2.loc[:,'Maths']
print(math_marks)

S1    43
S2    68
S3    25
S4    89
Name: Maths, dtype: int64


S1    43
S2    68
S3    25
S4    89
Name: Maths, dtype: int64

In [ ]:
df3 = df.copy()
df3.rename(index = {'S1':'Alice', 'S2':'Bob', 'S3':'Sanjay', 'S4':'John'}, inplace = True)
df3

        Physics  Chemistry  Maths  Biology
Alice        43         43     43       43
Bob          68         68     68       68
Sanjay       25         25     25       25
John         89         89     89       89

In [ ]:
print(df3.iloc[0,0:3], '\n\n')
print(df3.loc['Alice',['Physics','Chemistry','Maths']])

Physics      43
Chemistry    43
Maths        43
Name: Alice, dtype: int64


Physics      43
Chemistry    43
Maths        43
Name: Alice, dtype: int64

In [ ]:
df3['Total'] = df3.sum(axis=1)
print(df3)

        Physics  Chemistry  Maths  Biology  Total
Alice        43         43     43       43    172
Bob          68         68     68       68    272
Sanjay       25         25     25       25    100
John         89         89     89       89    356

In [ ]:
df3.loc['Total2'] = df.sum(axis=0)
print(df3)

       Index   Index  Physics  Chemistry  Maths  Biology  Total
0        0.0   Alice     43.0       43.0   43.0     43.0  172.0
1        1.0     Bob     68.0       68.0   68.0     68.0  272.0
2        2.0  Sanjay     25.0       25.0   25.0     25.0  100.0
3        3.0    John     89.0       89.0   89.0     89.0  356.0
4        4.0  Total2    225.0      225.0  225.0    225.0    NaN
Total2   NaN     NaN    225.0      225.0  225.0    225.0    NaN

In [ ]:
df

    Physics  Chemistry  Maths  Biology
S1     43.0       43.0   43.0     43.0
S2     68.0       68.0   68.0     68.0
S3     25.0       25.0   25.0     25.0
S4     89.0       89.0   89.0     89.0

In [ ]:
df3
df3.drop('Total2',axis = 0)
df3.reset_index()

    index Index   Index  Physics  Chemistry  Maths  Biology  Total
0       0   0.0   Alice     43.0       43.0   43.0     43.0  172.0
1       1   1.0     Bob     68.0       68.0   68.0     68.0  272.0
2       2   2.0  Sanjay     25.0       25.0   25.0     25.0  100.0
3       3   3.0    John     89.0       89.0   89.0     89.0  356.0
4       4   4.0  Total2    225.0      225.0  225.0    225.0    NaN
5  Total2   NaN     NaN    225.0      225.0  225.0    225.0    NaN

In [ ]:
df3.drop('Index',axis = 1)
df3.drop_duplicates()
df3

       Index   Index  Physics  Chemistry  Maths  Biology  Total
0        0.0   Alice     43.0       43.0   43.0     43.0  172.0
1        1.0     Bob     68.0       68.0   68.0     68.0  272.0
2        2.0  Sanjay     25.0       25.0   25.0     25.0  100.0
3        3.0    John     89.0       89.0   89.0     89.0  356.0
4        4.0  Total2    225.0      225.0  225.0    225.0    NaN
Total2   NaN     NaN    225.0      225.0  225.0    225.0    NaN

       Index   Index  Physics  Chemistry  Maths  Biology  Total
0        0.0   Alice     43.0       43.0   43.0     43.0  172.0
1        1.0     Bob     68.0       68.0   68.0     68.0  272.0
2        2.0  Sanjay     25.0       25.0   25.0     25.0  100.0
3        3.0    John     89.0       89.0   89.0     89.0  356.0
4        4.0  Total2    225.0      225.0  225.0    225.0    NaN
Total2   NaN     NaN    225.0      225.0  225.0    225.0    NaN

In [ ]:

df3 = df.copy()

df3.rename(index = {'S1':'Alice', 'S2':'Bob', 'S3':'Sanjay', 'S4':'John'}, inplace = True)

df3['Total'] = df3.sum(axis=1)
df3

        Physics  Chemistry  Maths  Biology  Total
Alice      43.0       43.0   43.0     43.0  172.0
Bob        68.0       68.0   68.0     68.0  272.0
Sanjay     25.0       25.0   25.0     25.0  100.0
John       89.0       89.0   89.0     89.0  356.0

In [ ]:
df4 = df3.T
df4

           Alice    Bob  Sanjay   John
Physics     43.0   68.0    25.0   89.0
Chemistry   43.0   68.0    25.0   89.0
Maths       43.0   68.0    25.0   89.0
Biology     43.0   68.0    25.0   89.0
Total      172.0  272.0   100.0  356.0

In [ ]:
df4_T = df4.T
print(df4)

        Physics  Chemistry  Maths  Biology  Total
Alice      43.0       43.0   43.0     43.0  172.0
Bob        68.0       68.0   68.0     68.0  272.0
Sanjay     25.0       25.0   25.0     25.0  100.0
John       89.0       89.0   89.0     89.0  356.0

In [ ]:
df5 = df4.sort_index(axis = 0, ascending = False)
df5

        Physics  Chemistry  Maths  Biology  Total
Sanjay     25.0       25.0   25.0     25.0  100.0
John       89.0       89.0   89.0     89.0  356.0
Bob        68.0       68.0   68.0     68.0  272.0
Alice      43.0       43.0   43.0     43.0  172.0

In [ ]:
df5 = df4.sort_values(by = 'Total', ascending = False)
df5
max_marks_physics = df5.iloc[0,0]
print(max_marks_physics)

89.0

In [ ]:
s1 = pd.Series({'Physics':43, 'Chemistry':68, 'Maths':0, 'Biology':89})
s2 = pd.Series({'Physics':43, 'Chemistry':68, 'Maths':0, 'Biology':89})
s3 = pd.Series({'Physics':43, 'Chemistry':68, 'Maths':0, 'Biology':89})
s4 = pd.Series({'Physics':43, 'Chemistry':68, 'Maths':0, 'Biology':89})

print(s1)

Physics      43
Chemistry    68
Maths         0
Biology      89
dtype: int64

In [ ]:
sum = s1 + s2
diff = s2-s1
prod = s1*s2
div = s1/s2
print(sum,'\n\n')
print(diff,'\n\n')
print(prod,'\n\n')
print(div,'\n\n')

fract = s1/100
print(fract)

Physics       86
Chemistry    136
Maths          0
Biology      178
dtype: int64


Physics      0
Chemistry    0
Maths        0
Biology      0
dtype: int64


Physics      1849
Chemistry    4624
Maths           0
Biology      7921
dtype: int64


Physics      1.0
Chemistry    1.0
Maths        NaN
Biology      1.0
dtype: float64


Physics      0.43
Chemistry    0.68
Maths        0.00
Biology      0.89
dtype: float64

In [ ]:
df = pd.DataFrame([sum, diff, prod, div], index = ['Sum','Diff','Prod','Div'])
print (df)

      Physics  Chemistry  Maths  Biology
Sum      86.0      136.0    0.0    178.0
Diff      0.0        0.0    0.0      0.0
Prod   1849.0     4624.0    0.0   7921.0
Div       1.0        1.0    NaN      1.0

In [ ]:
import seaborn as sns
Titanic = sns.load_dataset('titanic')
df = Titanic.copy()
df.sample(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
531,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
519,0,3,male,32.00,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
266,0,3,male,16.00,4,1,39.6875,S,Third,man,True,NaN,Southampton,no,False
81,1,3,male,29.00,0,0,9.5000,S,Third,man,True,NaN,Southampton,yes,True
699,0,3,male,42.00,0,0,7.6500,S,Third,man,True,F,Southampton,no,True
441,0,3,male,20.00,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
431,1,3,female,NaN,1,0,16.1000,S,Third,woman,False,NaN,Southampton,yes,False
871,1,1,female,47.00,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
890,0,3,male,32.00,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
#@title Pivoting
#average age of passengers
#grouped by gender and class, split by survival status

pd.pivot_table(df, index = ['sex','class'], columns = 'survived', values='age')

/tmp/ipykernel_22467/3661168360.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(df, index = ['sex','class'], columns = 'survived', values='age')

survived               0          1
sex    class
female First   25.666667  34.939024
       Second  36.000000  28.080882
       Third   23.818182  19.329787
male   First   44.581967  36.248000
       Second  33.369048  16.022000
       Third   27.255814  22.274211

In [ ]:
df.pivot_table( index = ['sex','class'], columns = 'survived', values='age')

/tmp/ipykernel_22467/165902923.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table( index = ['sex','class'], columns = 'survived', values='age')

survived               0          1
sex    class
female First   25.666667  34.939024
       Second  36.000000  28.080882
       Third   23.818182  19.329787
male   First   44.581967  36.248000
       Second  33.369048  16.022000
       Third   27.255814  22.274211

In [ ]:
pd.pivot_table(df, index = 'survived', columns = ['sex','pclass'], values = 'age', aggfunc = 'count', fill_value=0)

sex      female         male
pclass        1   2   3    1   2    3
survived
0             3   6  55   61  84  215
1            82  68  47   40  15   38

In [ ]:
df.pivot_table(index = 'survived', columns = ['sex','pclass'], values = 'age', aggfunc = 'median', fill_value=0)

sex      female              male
pclass        1     2     3     1     2     3
survived
0          25.0  32.5  22.0  45.5  30.5  25.0
1          35.0  28.0  19.0  36.0   3.0  25.0

In [ ]:
df.groupby(['sex','pclass'])['age'].mean()

sex     pclass
female  1         34.611765
        2         28.722973
        3         21.750000
male    1         41.281386
        2         30.740707
        3         26.507589
Name: age, dtype: float64

In [ ]:
df['fare'].mean()

np.float64(32.204207968574636)

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df = pd.read_csv('data_sales.csv')
df.head()

        Date   Region     Item  Unit Price  Units
0  04-Jul-14     East  Pen Set        4.99     62
1  12-Jul-14     East   Binder        1.99     29
2  21-Jul-14  Central  Pen Set       12.49     55
3  29-Jul-14     East   Binder       19.99     81
4  07-Aug-14  Central  Pen Set       23.95     42

In [ ]:
# Convert 'Date' column to datetime objects first
df['Date'] = pd.to_datetime(df['Date'])
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df['Day'] = df['Date'].dt.day

/tmp/ipykernel_22467/3328776454.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
total_units_region = df.groupby('Region')['Units'].sum()
print(total_units_region)

Region
Central    1199
East        691
West        231
Name: Units, dtype: int64

In [ ]:
df['Revenue'] = df['Units'] * df['Unit Price']
product_wise_sales = df.groupby('Item')[['Units', 'Revenue']].sum()
display(product_wise_sales)

         Units  Revenue
Item
Binder     722  9577.65
Desk        10  1700.00
Pen        278  2045.22
Pen Set    395  4169.87
Pencil     716  2135.14

In [ ]:
df.head()

        Date   Region     Item  Unit Price  Units  Revenue
0  04-Jul-14     East  Pen Set        4.99     62   309.38
1  12-Jul-14     East   Binder        1.99     29    57.71
2  21-Jul-14  Central  Pen Set       12.49     55   686.95
3  29-Jul-14     East   Binder       19.99     81  1619.19
4  07-Aug-14  Central  Pen Set       23.95     42  1005.90

In [ ]:
sorted_revenue = df.sort_values(by = 'Revenue', ascending = False)
sorted_revenue.head()

         Date   Region     Item  Unit Price  Units  Revenue
18  04-Dec-14  Central   Binder       19.99     94  1879.06
3   29-Jul-14     East   Binder       19.99     81  1619.19
25  01-Feb-15  Central   Binder       15.00     87  1305.00
21  29-Dec-14     East  Pen Set       15.99     74  1183.26
12  14-Oct-14     West   Binder       19.99     57  1139.43

In [ ]:
time_based = df.groupby('Date')['Revenue'].sum()
time_based.head()

Date
01-Apr-15     299.40
01-Feb-15    1305.00
01-Sep-14     250.00
04-Dec-14    1879.06
04-Jul-14     309.38
Name: Revenue, dtype: float64

In [ ]:
df['Quarter'] = df['Date'].dt.quarter

quarterly_revenue = df.groupby('Quarter')['Revenue'].sum()

print(quarterly_revenue)

Quarter
1    4203.29
2    3972.88
3    5344.89
4    6106.82
Name: Revenue, dtype: float64